"""
ban_detector.py — IP ban detection for Neluxmatizer scanners.

Logic:
  1. Each scanner records every HTTP response status per domain.
  2. When N consecutive blocked responses (403/429/503) are seen,
     a clean probe (GET to the domain root, no payload) is fired.
  3. If the clean probe is also blocked → IP is banned.
     Print a visible [IP BANNED] message with WAF name and mark the
     domain as banned so all scanners skip it.
  4. If the clean probe succeeds → WAF is just blocking payloads (normal).
     Continue silently; reset the consecutive counter.
"""

import threading
import requests
from urllib.parse import urlparse

# How many consecutive blocked responses before triggering the clean probe
BAN_THRESHOLD = 15

# HTTP status codes that indicate blocking
BLOCKED_STATUSES = {403, 429, 503, 429}

# WAF fingerprints: checked against response headers + body of the clean probe
_WAF_SIGNATURES: dict = {
    "Cloudflare":   ["cloudflare", "cf-ray", "__cfduid", "attention required", "error 1010"],
    "Akamai":       ["akamai", "reference #", "access denied - akamai"],
    "AWS WAF":      ["awswaf", "x-amzn-requestid", "aws-waf"],
    "F5 BIG-IP":    ["the requested url was rejected", "f5 networks"],
    "ModSecurity":  ["mod_security", "406 not acceptable", "modsecurity"],
    "Imperva":      ["incapsula", "imperva", "_incap_"],
    "Sucuri":       ["sucuri", "cloudproxy"],
    "Barracuda":    ["barracuda", "barra_counter_session"],
    "Wordfence":    ["wordfence", "generated by wordfence"],
}


def _detect_waf_from_response(response) -> str:
    """Return WAF name from a requests.Response, or 'Unknown WAF'."""
    headers_str = " ".join(
        f"{k}: {v}" for k, v in response.headers.items()
    ).lower()
    body_str = (response.text or "")[:2000].lower()
    combined = headers_str + " " + body_str
    for waf_name, sigs in _WAF_SIGNATURES.items():
        if any(sig in combined for sig in sigs):
            return waf_name
    return "Unknown WAF / Firewall"


class BanDetector:
    """
    Thread-safe per-domain IP ban detector.

    Usage in a scanner:
        detector = get_ban_detector()   # singleton per process
        ...
        if detector.is_banned(domain):
            return   # skip silently
        detector.record(domain, status_code, response_obj, base_url)
    """

    def __init__(self):
        self._lock = threading.Lock()
        # domain → count of consecutive blocked responses
        self._consecutive: dict[str, int] = {}
        # domains confirmed as IP-banned
        self._banned: set[str] = set()
        # domains where we already printed the ban message (avoid spam)
        self._reported: set[str] = set()

    def is_banned(self, domain: str) -> bool:
        with self._lock:
            return domain in self._banned

    def pre_check(self, url: str) -> bool:
        """
        Send a clean probe BEFORE starting any attacks.
        Returns True if the IP is already banned (caller should skip/exit).
        Returns False if the target is reachable.
        """
        parsed = urlparse(url)
        domain = parsed.netloc
        clean_url = f"{parsed.scheme}://{domain}/"

        with self._lock:
            if domain in self._banned:
                return True  # already confirmed banned

        blocked_status = 403
        try:
            probe = requests.get(
                clean_url,
                headers={"User-Agent": "Mozilla/5.0 (compatible; Googlebot/2.1)"},
                timeout=6,
                verify=False,
                allow_redirects=True,
            )
            if probe.status_code not in BLOCKED_STATUSES:
                return False  # reachable — go ahead
            blocked_status = probe.status_code
            waf_name = _detect_waf_from_response(probe)
        except requests.exceptions.ConnectionError:
            waf_name = "Unknown WAF / Firewall"
        except Exception:
            return False  # network issue — don't block, let the scanner handle it

        # Target is blocked even with a clean request
        with self._lock:
            self._banned.add(domain)
            if domain not in self._reported:
                self._reported.add(domain)
                _print_ban_message(domain, waf_name, blocked_status)
        return True

    def record(self, domain: str, status_code: int,
               response=None, base_url: str = "") -> None:
        """
        Call after every HTTP response.
        - domain: just the netloc, e.g. 'foundation.xyz'
        - status_code: HTTP status of the response
        - response: the requests.Response object (used for WAF detection)
        - base_url: full URL used to build the clean probe
        """
        do_check = False
        with self._lock:
            if domain in self._banned:
                return

            if status_code in BLOCKED_STATUSES:
                self._consecutive[domain] = self._consecutive.get(domain, 0) + 1
            else:
                # Non-blocked response: reset counter and continue attacking
                self._consecutive[domain] = 0
                return

            if self._consecutive.get(domain, 0) >= BAN_THRESHOLD:
                # Reset NOW inside the lock so only ONE thread fires the clean probe.
                # After the probe, if not banned, counter stays at 0 and accumulates
                # again — re-check triggers after every BAN_THRESHOLD blocked responses.
                self._consecutive[domain] = 0
                do_check = True

        if do_check:
            self._check_ban(domain, response, base_url)

    def _check_ban(self, domain: str, last_response, base_url: str) -> None:
        """Send a clean GET to the domain root and decide if IP is banned."""
        parsed = urlparse(base_url)
        clean_url = f"{parsed.scheme}://{parsed.netloc}/"

        clean_blocked = False
        blocked_status = 403
        waf_name = "Unknown WAF / Firewall"
        try:
            probe = requests.get(
                clean_url,
                headers={"User-Agent": "Mozilla/5.0 (compatible; Googlebot/2.1)"},
                timeout=6,
                verify=False,
                allow_redirects=True,
            )
            clean_blocked = probe.status_code in BLOCKED_STATUSES
            blocked_status = probe.status_code
            waf_name = _detect_waf_from_response(probe)
        except requests.exceptions.ConnectionError:
            clean_blocked = True  # cannot reach server at all
        except Exception:
            # Transient network issue — reset counter and continue
            with self._lock:
                self._consecutive[domain] = 0
            return

        with self._lock:
            if clean_blocked:
                self._banned.add(domain)
                if domain not in self._reported:
                    self._reported.add(domain)
                    self._consecutive[domain] = 0
                    _print_ban_message(domain, waf_name, blocked_status)
            else:
                # WAF blocks payloads but not our IP — reset and continue
                self._consecutive[domain] = 0


def _print_ban_message(domain: str, waf_name: str, status_code: int = 403) -> None:
    import sys
    if status_code == 429:
        label  = "\033[1;33m[!] [RATE LIMITED]\033[0m"
        reason = "Rate limited"
        hint   = "Try reducing threads (--threads) or adding a delay before retrying."
    else:
        label  = "\033[1;31m[!] [IP BLOCKED]\033[0m"
        reason = "IP blocked"
        hint   = "Try rotating your IP or using a proxy before retrying."

    msg = (
        f"\n{label} {reason} by \033[1;33m{waf_name}\033[0m"
        f" on \033[1;36m{domain}\033[0m. {hint}"
        f" Skipping further requests to this domain.\n"
    )
    sys.stdout.write(msg)
    sys.stdout.flush()


# ── Singleton ────────────────────────────────────────────────────────────────
_instance: BanDetector | None = None
_instance_lock = threading.Lock()


def get_ban_detector() -> BanDetector:
    """Return the process-wide BanDetector singleton."""
    global _instance
    if _instance is None:
        with _instance_lock:
            if _instance is None:
                _instance = BanDetector()
    return _instance
